#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
${symbol_pound}Enables the remote channel configuration. The jGroups channels will ne initialized by using the URL in the AALSpaceCard 
remoteChannelConfig=false

connectorName=jGroups Communication Connector
connectorVersion = 1.0
connectorProvider = ISTI-CNR
connectorDescription = JGroups Communication Connector